src/Entity/Candidat.php
<?php

namespace App\Entity;

use App\Repository\CandidatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Date;

#[ORM\Entity(repositoryClass: CandidatRepository::class)]
class Candidat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $genre = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $pays = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $nationalite = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lieu_naissance = null;


    #[ORM\Column(length: 100, nullable: true)]
    private ?string $job_categorie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $experience = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_create = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_uptaded = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_deleted = null;




    #[ORM\OneToOne(inversedBy: 'PassportCandidat', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)]
    private ?Media $passport = null;

    #[ORM\OneToOne(inversedBy: 'CvCandidat', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)]
    private ?Media $cv = null;

    #[ORM\OneToOne(inversedBy: 'ProfilPictureCandidat', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)]
    private ?Media $profil_picture = null;

    #[ORM\OneToMany(mappedBy: 'candidat', targetEntity: Candidature::class, orphanRemoval: true)]
    private Collection $Candidature;



    #[ORM\OneToOne(inversedBy: 'candidat', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    #[ORM\Column( nullable: true)]
    private ?\DateTimeImmutable $date_naissance = null;




    public function __construct()
    {
        $this->Candidature = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): static
    {
        $this->pays = $pays;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(?string $nationalite): static
    {
        $this->nationalite = $nationalite;

        return $this;
    }

 

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(?string $lieu_naissance): static
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }


    public function getJobCategorie(): ?string
    {
        return $this->job_categorie;
    }

    public function setJobCategorie(?string $job_categorie): static
    {
        $this->job_categorie = $job_categorie;

        return $this;
    }

    public function getExperience(): ?string
    {
        return $this->experience;
    }

    public function setExperience(?string $experience): static
    {
        $this->experience = $experience;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(?\DateTimeInterface $date_create): static
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getDateUptaded(): ?\DateTimeInterface
    {
        return $this->date_uptaded;
    }

    public function setDateUptaded(?\DateTimeInterface $date_uptaded): static
    {
        $this->date_uptaded = $date_uptaded;

        return $this;
    }

    public function getDateDeleted(): ?\DateTimeInterface
    {
        return $this->date_deleted;
    }

    public function setDateDeleted(?\DateTimeInterface $date_deleted): static
    {
        $this->date_deleted = $date_deleted;

        return $this;
    }



    public function getPassport(): ?Media
    {
        return $this->passport;
    }

    public function setPassport(?Media $passport): static
    {
        $this->passport = $passport;

        return $this;
    }

    public function getCv(): ?Media
    {
        return $this->cv;
    }

    public function setCv(?media $cv): static
    {
        $this->cv = $cv;

        return $this;
    }

    public function getProfilPicture(): ?Media
    {
        return $this->profil_picture;
    }

    public function setProfilPicture(?Media $profil_picture): static
    {
        $this->profil_picture = $profil_picture;

        return $this;
    }

    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidature(): Collection
    {
        return $this->Candidature;
    }

    public function addCandidature(Candidature $candidature): static
    {
        if (!$this->Candidature->contains($candidature)) {
            $this->Candidature->add($candidature);
            $candidature->setCandidat($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): static
    {
        if ($this->Candidature->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getCandidat() === $this) {
                $candidature->setCandidat(null);
            }
        }

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(User $User): static
    {
        $this->User = $User;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeImmutable
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeImmutable $date_naissance): static
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }




   
}

src/Controller/CandidatController.php
<?php

namespace App\Controller;

use App\Entity\Candidat;
use App\Entity\Media;
use App\Entity\User;
use App\Form\CandidatType;
use App\Repository\CandidatRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Uid\Uuid;

#[Route('/candidat')]
class CandidatController extends AbstractController
{
    #[Route('/', name: 'app_candidat_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {

        $candidat = new Candidat();


        /**
         **@var User $user
         */

        $user = $this->getUser();
        $candidat = $user->getCandidat();

        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {


            $allConditionsMet = true;
            
            if ($form['profil_picture']->getData()) {
                /**
                 **@var UploadedFile $profilPictureFile 
                 */
                $profilPictureFile = $form['profil_picture']->getData();
                $profilPictureName = Uuid::v7();

                $extension = $profilPictureFile->guessExtension();
                if (!$extension) {
                    $extension = 'png';
                }

                $profilPictureName = $profilPictureName . '.' . $extension;

                $profilPictureFile->move('media/profilPictures', $profilPictureName);

                $profilPictureMedia = new Media();
                $profilPictureMedia->setUrl($profilPictureName);
                $profilPictureMedia->setOriginalName($profilPictureFile->getClientOriginalName());

                $entityManager->persist($profilPictureMedia);

                $candidat->setProfilPicture($profilPictureMedia);
                $entityManager->persist($candidat);

            } else {
                $allConditionsMet = false;
            }


            if ($form['cv']->getData()) {
                /**
                 **@var UploadedFile $cvPictureFile 
                 */
                $cvPictureFile = $form['cv']->getData();
                $cvPictureName = Uuid::v7();

                $extension = $cvPictureFile->guessExtension();
                if (!$extension) {
                    $extension = 'png';
                }

                $cvPictureName = $cvPictureName . '.' . $extension;

                $cvPictureFile->move('media/cvPictures', $cvPictureName);

                $cvPictureMedia = new Media();
                $cvPictureMedia->setUrl($cvPictureName);
                $cvPictureMedia->setOriginalName($cvPictureFile->getClientOriginalName());

                $entityManager->persist($cvPictureMedia);

                $candidat->setCv($cvPictureMedia);
                $entityManager->persist($candidat);

            } else {
                $allConditionsMet = false; // Si cette condition n'est pas remplie, définissez la variable à false
            }


            if ($form['passport']->getData()) {
                /**
                 **@var UploadedFile $passportPictureFile
                 */
                $passportPictureFile = $form['passport']->getData();

                $passportPictureName = Uuid::v7();

                $extension = $passportPictureFile->guessExtension();
                if (!$extension) {
                    $extension = 'png';
                }

                $passportPictureName = $passportPictureName . '.' . $extension;

                $passportPictureFile->move('media/passportPictures', $passportPictureName);

                $passportPictureMedia = new Media();
                $passportPictureMedia->setUrl($passportPictureName);
                $passportPictureMedia->setOriginalName($passportPictureFile->getClientOriginalName());

                $entityManager->persist($passportPictureMedia);

                $candidat->setPassport($passportPictureMedia);
                $entityManager->persist($candidat);

            } else {
                $allConditionsMet = false; // Si cette condition n'est pas remplie, définissez la variable à false
            }


            // if ($allConditionsMet) {
            //     // $user->setRoles(['ROLE_CANDIDAT']);
            //     // $entityManager->persist($user);
            // }
            $entityManager->flush();

            return $this->redirectToRoute('app_candidat_new');
        }

        return $this->render('candidat/new.html.twig', [
            'candidat' => $candidat,
            'form' => $form,
        ]);
    }
}

templates/candidat/_form.html.twig
{{ form_start(form)}}
<section class="section-padding">
	<div class="container">
		<div class="row">
			<h3 class="text-extrabold">Your personal informations</h3>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="input-field">
					{{ form_widget(form.genre) }}
					<label for="gender" class="active">Gender</label>
				</div>
			</div>
			<div class="clearfix visible-sm"></div>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="input-field">
					{{ form_widget(form.nom) }}
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="input-field">
					{{ form_widget(form.prenom) }}

				</div>
			</div>
			<div class="col-xs-12 col-sm-8">
				<div class="input-field">
					{{ form_widget(form.adresse) }}
				</div>
			</div>
		</div>


		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="file-field input-field" style="margin-top: 32px;">
					<div class="btn btn-lg primary waves-effect waves-light">
						<span>
							<i class="material-icons">insert_photo</i>
							Photo</span>
						{{ form_widget(form.profil_picture) }}
						<!-- <input id="photo" size="20000000" accept=".pdf,.jpg,.doc,.docx,.png,.gif" name="photo" type="file"> -->
					</div>

					{% if candidat.profilPicture %}

						<div class="existing-file">
							<a href="{{ asset ('media/profilPictures/') }} {{ candidat.profilPicture.url }}" target="_blank">
								<i class="material-icons">&#xE24D;</i>
								{{ candidat.profilPicture.originalName }}</a>
						</div>
						<div class="file-path-wrapper">
							<input class="file-path validate" type="text" placeholder="Upload your ID photo" readonly>
						</div>
					{% endif %}
				</div>
			</div>


			<div class="col-xs-12 col-sm-6 col-md-8">
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="input-field">
							{{ form_widget(form.pays) }}

						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="input-field">
							{{ form_widget(form.nationalite) }}

						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="input-field">
							{{ form_widget(form.date_naissance) }}

						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="input-field">
							{{ form_widget(form.lieu_naissance) }}

						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row mt-40">
			<h3 class="text-extrabold">Your professional profile</h3>
			<div class="col-xs-12 col-sm-6">

				<div class="card card-panel passport">
					<div class="file-field input-field">
						<div class="btn btn-lg primary waves-effect waves-light">
							<span>
								<i class="material-icons">&#xE24D;</i>
								Passport</span>
							{{ form_widget(form.passport) }}
						</div>
						{% if candidat.passport %}
							<div class="existing-file">
								<a href="{{ asset ('media/passportPictures/') }} {{ candidat.passport.url }}" target="_blank">
									<i class="material-icons">&#xE24D;</i>
									{{ candidat.passport.originalName }}</a>
							</div>
							<div class="file-path-wrapper">
								<input class="file-path validate" type="text" placeholder="Upload your passport" readonly>
							</div>
						{% endif %}

					</div>

					<div class="file-field input-field">
						<div class="btn btn-lg primary waves-effect waves-light">
							<span>
								<i class="material-icons">&#xE24D;</i>
								CV</span>
							{{ form_widget(form.cv) }}
						</div>
						{% if candidat.cv %}

							<div class="existing-file">
								<a href="{{ asset ('media/cvPictures/') }} {{ candidat.cv.url }}" target="_blank">
									<i class="material-icons">&#xE24D;</i>
									{{ candidat.cv.originalName }}</a>
							</a>
						</div>
						<div class="file-path-wrapper">
							<input class="file-path validate" type="text" placeholder="Upload your Curriculum Vitae" readonly>
						</div>
					{% endif %}
				</div>

			</div>
		</div>

		<div class="col-xs-12 col-sm-6">
			<div class="col-xs-12 col-sm-12">
				<div class="input-field" style="margin-top: 5px;">
					{{ form_widget(form.job_categorie) }}

					<label for="job_sector" class="active">Interest in job sector</label>
				</div>
			</div>
			<div class="col-xs-12 col-sm-12">
				<div class="input-field">
					{{ form_widget(form.experience) }}
					<label for="experience" class="active">Experience</label>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12">
			<div class="input-field">
				{{ form_widget(form.description) }}
			</div>
		</div>
	</div>
</div></section><section class="section-padding gray-bg">
<div class="container">
	<div class="row">
		<h3 class="text-extrabold">Your K-Yachting account</h3>
		<div class="col-xs-12 col-sm-4">
			<div class="input-field">
				<input required="required" id="email" name="email" type="email" value="">
				<label for="email">Email</label>
			</div>
		</div>
		<div class="col-xs-12 col-sm-4">
			<div class="input-field">
				<input id="password" name="password" type="password" value="">
				<label for="password">Change your password here</label>
			</div>
		</div>
		<div class="col-xs-12 col-sm-4">
			<div class="input-field">
				<input id="password_repeat" name="password_repeat" type="password" value="">
				<label for="password_repeat">Confirm your new password</label>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 mt-40 mb-80 delete-account">
			<a href="#!" onclick="return prompt('Please Type \'Delete my account\' to delete your K-Yachting Services account:') == 'Delete my account'" class="btn btn-block btn-lg waves-effect waves-light">
				<i class="material-icons">&#xE872;</i>Delete my account</a>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-4">
			<a href="#!" class="btn btn-block btn-lg border primary waves-effect waves-light">
				<i class="fa fa-long-arrow-left"></i>
				Back home</a>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4 col-md-offset-4">
			<button type="submit" class="btn btn-block btn-lg gradient secondary waves-effect waves-light">
				<span>
					<strong>UPDATE</strong>
					NOW</span>
			</button>
		</div>
	</div>

</div></section>{{ form_end(form) }}